  version: '3.7'

  services:
    db:
      image: postgres:11
      restart: always
      environment:
        - "POSTGRES_PASSWORD=postgresd"
        - "POSTGRES_USER=postgres"
        - "POSTGRES_DB=postgres"
      volumes:
        - postgres_data:/var/lib/postgresql/data/
    web:
      build:
        context: .
      ports:
        - "8000:8000"
      volumes:
        - .:/app
      command: sh -c "python manage.py runserver 0.0.0.0:8000"
      env_file:
        - ./.env.dev
      depends_on:
        - db


  volumes:
    postgres_data: