# Generated by Django 3.0.9 on 2020-09-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructor', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='F1Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gamef1')),
                ('chassis', models.CharField(blank=True, max_length=50)),
                ('constructor', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(blank=True, max_length=4)),
            ],
        ),
    ]
