# Generated by Django 3.0.9 on 2020-09-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0002_auto_20200913_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f1prediction',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='f1prediction',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
