# Generated by Django 3.0.3 on 2020-03-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0002_gamephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePhoto',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
