# Generated by Django 3.1.1 on 2020-10-08 01:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0003_auto_20200913_0328'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='f1prediction',
            managers=[
                ('cars', django.db.models.manager.Manager()),
            ],
        ),
    ]
