# Generated by Django 3.0.3 on 2020-03-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamef1', '0003_auto_20200305_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('prediction', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
