# Generated by Django 3.0.3 on 2020-04-07 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0004_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classification',
        ),
    ]
