# Generated by Django 3.0.3 on 2020-04-07 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamef1', '0005_delete_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='F1Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_image', models.CharField(max_length=2000)),
            ],
        ),
    ]
