# Generated by Django 3.0.3 on 2020-04-07 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0006_f1model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='f1model',
            old_name='f1_image',
            new_name='f1image',
        ),
    ]
