# Generated by Django 3.0.3 on 2020-04-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0007_auto_20200406_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='f1model',
            name='f1text',
            field=models.CharField(default='Vai se fuder', max_length=100),
        ),
        migrations.AlterField(
            model_name='f1model',
            name='f1image',
            field=models.CharField(max_length=200),
        ),
    ]
