# Generated by Django 3.0.3 on 2020-04-07 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0009_remove_f1model_f1text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='F1Model',
            new_name='modeltest',
        ),
    ]
