# Generated by Django 3.0.3 on 2020-04-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0011_auto_20200406_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formula',
            old_name='image',
            new_name='imagelink',
        ),
    ]
