# Generated by Django 3.0.4 on 2020-04-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0013_formula_imagephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='imagelink',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='formula',
            name='imagephoto',
            field=models.ImageField(upload_to='gamef2/'),
        ),
    ]
