# Generated by Django 3.0.4 on 2020-04-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0014_auto_20200428_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='imagelink',
        ),
        migrations.RemoveField(
            model_name='formula',
            name='imagephoto',
        ),
        migrations.AddField(
            model_name='formula',
            name='f1image',
            field=models.ImageField(default=1, upload_to='gamef1/'),
            preserve_default=False,
        ),
    ]
