# Generated by Django 3.0.4 on 2020-05-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0015_auto_20200428_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.CharField(max_length=100)),
            ],
        ),
    ]
