# Generated by Django 3.0.4 on 2020-05-01 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0016_formula_f1text'),
        ('gamef1', '0016_answer'),
    ]

    operations = [
    ]
