# Generated by Django 3.0.4 on 2020-05-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0016_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='chassis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='answer',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='answer',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
