# Generated by Django 3.0.4 on 2020-05-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0017_merge_20200501_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='f1text',
        ),
    ]
