# Generated by Django 3.0.4 on 2020-05-01 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0018_remove_formula_f1text'),
        ('gamef1', '0017_auto_20200430_2210'),
    ]

    operations = [
    ]
