# Generated by Django 3.0.4 on 2020-05-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0019_merge_20200501_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='guess',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
