# Generated by Django 3.0.4 on 2020-05-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamef1', '0020_auto_20200501_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='guess',
            field=models.CharField(max_length=100),
        ),
    ]
