# Generated by Django 3.0.3 on 2020-03-27 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawnumber', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
