# Generated by Django 3.0.3 on 2020-04-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drawnumber', '0002_delete_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing', models.FileField(upload_to='numbers/draw/')),
            ],
        ),
    ]
