# Generated by Django 3.0.3 on 2020-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawnumber', '0003_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='drawing',
            field=models.CharField(max_length=2000),
        ),
    ]
