# Generated by Django 3.0.3 on 2020-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawnumber', '0004_auto_20200406_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='drawingcode',
            field=models.TextField(default='2', max_length=2000),
        ),
        migrations.AlterField(
            model_name='number',
            name='drawing',
            field=models.CharField(max_length=100),
        ),
    ]
