# Generated by Django 3.0.3 on 2020-04-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawnumber', '0005_auto_20200406_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='drawingcode',
        ),
    ]
